#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# SLP Context Compact Compiler Script
# Compiles herdr-context/<peer>/_state/context-compact.md (<= 5 KB cache)
# ==============================================================================

if [ $# -lt 1 ]; then
  echo "Usage: $0 <peer-name> [workspace-root]"
  exit 1
fi

PEER="$1"
WORKSPACE_ROOT="${2:-$(pwd)}"
DIR="$WORKSPACE_ROOT/herdr-context/$PEER"
STATE="$DIR/_state/status.json"
COMPACT="$DIR/_state/context-compact.md"

if [ ! -f "$STATE" ]; then
  echo "Error: State file not found at $STATE"
  exit 1
fi

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

{
  echo "# Peer Compact — $PEER"
  echo "**Generated:** $NOW"
  jq -r '"**Tier:** \(.tier)\n**State:** \(.state)"' "$STATE"

  echo
  echo "## Current State"
  jq -r '"- state: \(.state)\n- current_task: \(.current_task // "none")\n- last_completed: \(.last_task // "none") at \(.last_completed_at // "?")\n- last_summary: \(.last_answer_summary // "n/a")"' "$STATE"

  echo
  echo "## Recurring Constraints"
  echo "**DO:**"
  jq -r '(.known_constraints.do // [])[]' "$STATE" | sed 's/^/- /'
  echo "**DO NOT:**"
  jq -r '(.known_constraints.do_not // [])[]' "$STATE" | sed 's/^/- /'

  echo
  echo "## Recent Handbacks (Last 5)"
  ANSWERS=$( (ls "$DIR" 2>/dev/null | grep -E '^[0-9]{3}-answer' || true) | sort -r | head -5)
  if [ -z "$ANSWERS" ]; then
    echo "- (No completed tasks yet)"
  else
    echo "$ANSWERS" | while read -r f; do
      [ -z "$f" ] && continue
      nnn=$(echo "$f" | cut -c1-3)
      title=$(grep -m1 '^# HANDBACK [0-9]\{3\} — ' "$DIR/$f" 2>/dev/null | sed 's/^# HANDBACK [0-9]\{3\} — //' || true)
      [ -n "$title" ] || title=$(grep -m1 '^# Answer [0-9]\{3\} — ' "$DIR/$f" 2>/dev/null | sed 's/^# Answer [0-9]\{3\} — //' || true)
      [ -n "$title" ] || title="untitled"
      disp=$(grep -m1 '^\*\*Disposition:\*\*' "$DIR/$f" 2>/dev/null | sed 's/^\*\*Disposition:\*\* //' || true)
      [ -n "$disp" ] || disp="CONFIRMED"
      echo "- **$nnn** [$disp] $title"
    done
  fi

  echo
  echo "## Active Risks"
  jq -r '(.known_risks // [])[]' "$STATE" | sed 's/^/- /'

  echo
  echo "## Open Questions"
  jq -r '(.open_questions // [])[] | "- Q: \(.question) (raised in \(.raised_in))"' "$STATE"

  echo
  echo "---"
  echo "*Generated by slp-state. Source of truth remains status.json and handback artifacts.*"
} > "$COMPACT"

echo "✔ Successfully updated $COMPACT"
