/**
 * GENERATED by scripts/gen-registry.ts — DO NOT EDIT.
 *
 * Single source of truth is src/screens/manifest.ts;
 * run `npm run screens:sync` (or `npm run new-screen`)
 * after editing it. index.ts only re-exports this.
 */
import moodCalendar from '../../project/moodtracker/mood-calendar.html?raw'
import journal from '../../project/moodtracker/journal.html?raw'
import home from '../../project/moodtracker/home.html?raw'

const RAW: Record<string, string> = {
  'mood-calendar': moodCalendar,
  'journal': journal,
  'home': home,
}

export function rawFor(id: string): string | undefined {
  return RAW[id]
}

export function rawIds(): string[] {
  return Object.keys(RAW)
}
