#!/usr/bin/env node
// @ts-nocheck — small zero-dep cli, checked by running it, not by tsc
/**
 * Registry generator (4.4): single source of truth = src/screens/manifest.ts
 * and src/components/manifest.ts.
 *
 *   npm run screens:sync     # regenerates both registries
 *   npm run components:sync  # same command — one generator, two files
 *
 * Regenerates `src/screens/generated.ts` and `src/components/generated.ts`
 * (both checked in): one static `?raw` import per entry + a raw map, so a
 * manifest entry with no file throws at startup instead of rendering blank.
 * `index.ts` only re-exports it, so hand-adding a screen/component is exactly
 * one manifest entry plus this command (and `new-screen` runs it for you).
 */

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { SCREEN_FILES } from '../src/screens/manifest.ts'
import { COMPONENT_FILES } from '../src/components/manifest.ts'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

function varName(id) {
  const v = id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
  const safe = v.replace(/[^a-zA-Z0-9_$]/g, '')
  return /^[0-9]/.test(safe) ? `s${safe}` : safe
}

function assertUnique(entries, label) {
  const seen = new Set()
  for (const e of entries) {
    if (seen.has(e.id)) throw new Error(`duplicate ${label} id "${e.id}" in manifest.ts`)
    seen.add(e.id)
  }
}

async function writeRegistry(outRel, entries, label) {
  const out = path.join(ROOT, outRel)
  const imports = entries.map((e) => `import ${varName(e.id)} from '../../${e.file}?raw'`)
  const raws = entries.map((e) => `  '${e.id}': ${varName(e.id)},`)
  const src = `/**
 * GENERATED by scripts/gen-registry.ts — DO NOT EDIT.
 *
 * Single source of truth is ${label === 'screen' ? 'src/screens' : 'src/components'}/manifest.ts;
 * run \`npm run ${label === 'screen' ? 'screens' : 'components'}:sync\` (or \`npm run new-screen\`)
 * after editing it. index.ts only re-exports this.
 */
${imports.join('\n')}

const RAW: Record<string, string> = {
${raws.join('\n')}
}

export function rawFor(id: string): string | undefined {
  return RAW[id]
}

export function rawIds(): string[] {
  return Object.keys(RAW)
}
`
  await writeFile(out, src)
}

async function main() {
  assertUnique(SCREEN_FILES, 'screen')
  assertUnique(COMPONENT_FILES, 'component')

  await writeRegistry('src/screens/generated.ts', SCREEN_FILES, 'screen')
  await writeRegistry('src/components/generated.ts', COMPONENT_FILES, 'component')

  console.log(`generated.ts: ${SCREEN_FILES.length} screens, ${COMPONENT_FILES.length} components`)
}

main().catch((e) => {
  console.error(`gen-registry: ${e instanceof Error ? e.message : String(e)}`)
  process.exit(1)
})
