#!/usr/bin/env node
// @ts-nocheck — small zero-dep cli, checked by running it, not by tsc
/**
 * Registry generator (4.4): single source of truth = src/screens/manifest.ts.
 *
 *   npm run screens:sync
 *
 * Regenerates `src/screens/generated.ts` (checked in): one static `?raw`
 * import per screen + the RAW map + a manifest/RAW consistency check that
 * throws at startup instead of rendering a blank frame. `index.ts` only
 * re-exports it, so hand-adding a screen is exactly one manifest entry
 * plus this command (and `new-screen` runs it for you).
 */

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { SCREEN_FILES } from '../src/screens/manifest.ts'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(ROOT, 'src/screens/generated.ts')

function varName(id) {
  const v = id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
  const safe = v.replace(/[^a-zA-Z0-9_$]/g, '')
  return /^[0-9]/.test(safe) ? `s${safe}` : safe
}

async function main() {
  const seen = new Set()
  for (const s of SCREEN_FILES) {
    if (seen.has(s.id)) throw new Error(`duplicate screen id "${s.id}" in manifest.ts`)
    seen.add(s.id)
  }

  const imports = SCREEN_FILES.map(
    (s) => `import ${varName(s.id)} from '../../${s.file}?raw'`,
  )
  const raws = SCREEN_FILES.map((s) => `  '${s.id}': ${varName(s.id)},`)

  const src = `/**
 * GENERATED by scripts/gen-registry.ts — DO NOT EDIT.
 *
 * Single source of truth is src/screens/manifest.ts; run \`npm run screens:sync\`
 * (or \`npm run new-screen\`) after editing it. index.ts only re-exports this.
 */
${imports.join('\n')}

const RAW: Record<string, string> = {
${raws.join('\n')}
}

export function rawFor(id: string): string | undefined {
  return RAW[id]
}

export function rawIds(): string[] {
  return Object.keys(RAW)
}
`
  await writeFile(OUT, src)
  console.log(`generated.ts: ${SCREEN_FILES.length} screens`)
}

main().catch((e) => {
  console.error(`gen-registry: ${e instanceof Error ? e.message : String(e)}`)
  process.exit(1)
})
